# Generated by Django 3.1.3 on 2020-12-03 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('textbook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.textbook')),
            ],
        ),
        migrations.CreateModel(
            name='Set_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('negotiable', models.BooleanField(default=False)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller')),
                ('textbook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.textbook')),
            ],
        ),
    ]
